language: java

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh  # Get latest install-jdk.sh script
  - unset _JAVA_OPTIONS  # https://github.com/travis-ci/travis-ci/issues/8408

matrix:
  include:
    - env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL

branches:
  only:
  - master
addons:
  sonarcloud:
    organization: "doi9t-github"
script:
  # other script steps might be done before running the actual SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

before_deploy:
  - git tag "release-$(date +'%Y%m%d%H%M%S')"
deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key: $GITHUB_OAUTH_TOKEN
  file: target/echechess-*.jar